### ISSUE TITLE
python: files that do not end in newlines are not parseable

### ISSUE THREAD

**Issue by asottile** [bukzor/RefactorLib#28]
```
$ echo -n 'print("hello world")' > test.py && xmlfrom test.py
Traceback (most recent call last):
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/bin/xmlfrom", line 9, in <module>
    load_entry_point('refactorlib==0.11.0', 'console_scripts', 'xmlfrom')()
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/cli/xmlfrom.py", line 25, in cli
    return main(argv, stdout)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/cli/xmlfrom.py", line 19, in main
    stdout.write(xmlfrom(argv[1]))
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/cli/xmlfrom.py", line 11, in xmlfrom
    tree = parse(filename).getroottree()
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/parse.py", line 18, in parse
    return filetype.parser(source, encoding)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/python/parse.py", line 28, in parse
    lib2to3_python = lib2to3_parse(python_contents)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/refactorlib/python/parse.py", line 53, in lib2to3_parse
    tree = py2_driver.parse_string(python_contents, True)
  File "/usr/lib64/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python2.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=0, value='', context=('\n', (2, 0))
```

**Comment by asottile** [comment]
Dupe #6
